-include .env

.PHONY: all test deploy

build :; forge build

test :; forge test 

install :; forge install cyfrin/foundry-devops && forge install smartcontractkit/chainlink-brownie-contracts && forge install transmissions11/solmate

update :; forge update

format :; forge fmt 

coverage :; forge coverage 

snapshot :; forge snapshot

anvil :; anvil -m 'test test test test test test test test test test test junk' --steps-tracing --block-time 1

deploy-sepolia :
	@forge script script/DeployRaffle.s.sol:DeployRaffle --rpc-url $(SEPOLIA_RPC_URL) --account sepolia --broadcast --verify -vvvv